# Generated by Django 4.2.2 on 2023-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus_rename_currency_type_rate_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=12)),
                ('address_change', models.CharField(max_length=255)),
            ],
        ),
    ]
