# Generated by Django 4.2.2 on 2023-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_source_logo_height_source_logo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.ImageField(default='source_logos/default_logo.png', upload_to='source_logos/'),
        ),
        migrations.AlterField(
            model_name='source',
            name='logo_height',
            field=models.PositiveIntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='source',
            name='logo_width',
            field=models.PositiveIntegerField(default=64),
        ),
    ]
